app/urls.py
from django.urls import path
from .views import ItemFilterView, ItemDetailView, ItemCreateView, ItemUpdateView, ItemDeleteView


urlpatterns = [
    # 一覧画面
    path('',  ItemFilterView.as_view(), name='index'),
    # 詳細画面
    path('detail/<int:pk>/', ItemDetailView.as_view(), name='detail'),
    # 登録画面
    path('create/', ItemCreateView.as_view(), name='create'),
    # 更新画面
    path('update/<int:pk>/', ItemUpdateView.as_view(), name='update'),
    # 削除画面
    path('delete/<int:pk>/', ItemDeleteView.as_view(), name='delete'),
]

crud/urls.py
# from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'crud'

urlpatterns = [
    path('members/', views.index, name='index'),
    path('members/add/', views.edit, name='add'),
    path('members/edit/<int:id>/', views.edit, name='edit'),
    path('members/delete/<int:id>/', views.delete, name='delete'),
    path('members/detail/<int:id>/', views.detail, name='detail'),
]

# url(r'^members/$', views.index, name='index'),
# url(r'^members/add/$', views.edit, name='add'),
# url(r'^members/edit/(?P<id>\d+)/$', views.edit, name='edit'),
# url(r'^members/delete/(?P<id>\d+)/$', views.delete, name='delete'),
# url(r'^members/detail/(?P<id>\d+)/$', views.detail, name='detail'),

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
# from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('todo/', include('todo.urls')),
    path('crud/', include('crud.urls')),
    path('employee/', include('employee.urls')),
    path('app/', include('app.urls')),
    path('', include('pdfmr.urls')),
]

crud/models.py
from django.db import models


class Member(models.Model):
    name = models.CharField('氏名', max_length=255)
    email = models.CharField('E-Mail', max_length=255)
    age = models.IntegerField('年齢', blank=True, default=0)

    def __str__(self):
        return self.name

crud/forms.py
from django.forms import ModelForm
from crud.models import Member


class MemberForm(ModelForm):
    class Meta:
        model = Member
        fields = ('name', 'email', 'age',)

crud/views.py
from django.shortcuts import render
from django.http import HttpResponse
from crud.models import Member
from crud.forms import MemberForm
from django.shortcuts import get_object_or_404, redirect


# 一覧
def index(request):
    members = Member.objects.all().order_by('id')  # 値を取得
    # return render(request, 'crud/index.html', {'members': members})  # Templateに値を渡す
    return render(request, 'members/index.html', {'members': members})  # Templateに値を渡す


# 新規と編集
def edit(request, id=None):

    if id:  # idがあるとき（編集の時）
        # idで検索して、結果を戻すか、404エラー
        member = get_object_or_404(Member, pk=id)
    else:  # idが無いとき（新規の時）
        # Memberを作成
        member = Member()

    # POSTの時（新規であれ編集であれ登録ボタンが押されたとき）
    if request.method == 'POST':
        # フォームを生成
        form = MemberForm(request.POST, instance=member)
        if form.is_valid():  # バリデーションがOKなら保存
            member = form.save(commit=False)
            member.save()
            return redirect('crud:index')
    else:  # GETの時（フォームを生成）
        form = MemberForm(instance=member)

    # 新規・編集画面を表示
    return render(request, 'members/edit.html', dict(form=form, id=id))


# 削除
def delete(request, id=None):
    return HttpResponse("削除")


# 詳細（おまけ）
def detail(request, id=None):
    return HttpResponse("詳細")

crud/templates/members/edit.html
{% extends "base.html" %}
{# {% load bootstrap %} #}

{% block title %}会員の編集{% endblock title %}

{% block content %}
    {% if id %}
    <h3 class="page-header">会員の編集</h3>
    <form action="{% url 'crud:edit' id=id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <h3 class="page-header">会員の登録</h3>
    <form action="{% url 'crud:add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      {# {{ form|bootstrap_horizontal }} #}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'crud:index' %}" class="btn btn-default btn-sm">戻る</a>
{% endblock content %}

crud/templates/members/index.html
{% extends 'base.html' %}

{% block title %}
一覧を表示する予定
{% endblock title %}

{% block content %}
<h3>一覧表示</h3>

<a href="{% url 'crud:add' %}" class="btn btn-primary btn-sm">追加</a>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>氏名</th>
            <th>E-Mail</th>
            <th>年齢</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
        {% for member in members %}
        <tr>
            <td>{{ member.id }}</td>
            <td><a href="{% url 'crud:detail' id=member.id %}">{{ member.name }}</a></td>
            <td>{{ member.email }}</td>
            <td>{{ member.age }}</td>
            <td>
                <a href="{% url 'crud:edit' id=member.id %}" class="btn btn-primary btn-sm">編集</a>
                <a href="{% url 'crud:delete' id=member.id %}" class="btn btn-primary btn-sm" id="btn_del">削除</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<!-- ページネーションをここに入れる -->

{% endblock content %}

<!-- jsを入れる -->
{% block script %}
{% endblock %}